version: '3'
services:
  backend_app:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    restart: always
    environment:
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_USER=${DB_USER_NAME}
      - DATABASE_PASSWORD=${DB_USER_PASSWORD}
      - DATABASE_NAME=${DB_DATABASE_NAME}
      - DATABASE_PORT=${DB_PORT}
    depends_on:
      - mysql
    networks:
      - hotels-network

  mysql:
    image: mysql:8.0.21
    restart: always
    command: --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      hotels-network:
        aliases:
          - mysql

networks:
  hotels-network:
    driver: bridge
